<a href="https://colab.research.google.com/github/Huyu2239/Prog2kakushin/blob/work2/work2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 第13回(1/12) numpy
- ２つの行列,`A`と`B`を入力
- `A`と`B`について以下の項目について出力(随時追加)
    - 逆行列
    - 転置
    - Rank
    - 積

In [73]:
import numpy as np

calc_dict = {
    "AA": "A*A",
    "AB": "A*B",
    "BA": "B*A",
    "BB": "B*B",
    "tAtA": "A.T*A.T",
    "tAtB": "A.T*B.T",
    "tBtA": "B.T*A.T",
    "tBtB": "B.T*B.T",
    "AtB": "A*B.T",
    "tAB": "A.T*B",
    "BtA": "B*A.T",
    "tBA": "B.T*A"
}

def show_matrix(mat):
    mat = np.array(mat)
    for m in mat:
        # print(" ".join(map(str, list(m))))
        print(m)


def get_matrix():
    while True:
        try:
            y, x = map(int, input("入力する行列の型を入力してください。\n例: 3,4 -> (3,4)行列").split(","))
        except Exception:
            print("Error: もう一度入力してください。")
            continue
        break
    array = []
    i = 0
    while i < y:
        row = list(map(int, input(f"{i+1}行目: ").split()))
        if len(row) != x:
            print("Error: もう一度入力してください。")
            continue
        array.append(row)
        i += 1
    return np.matrix(array)


def app(test=False):
# 使用する行列の入力
    if test:
        A = np.matrix([[1, -2, 3],[3, 1, -5],[-2, 6, -9]])
        B = np.matrix(np.ones((3, 4)))
    else:
        print("1つめの行列を入力してください")
        A = get_matrix()
        print("-"*15)
        print("2つめの行列を入力してください")
        B = get_matrix()
        print("-"*15)
        print("")

# 入力した行列の表示
    print("入力行列表示")
    print("A:")
    show_matrix(A)
    print("")
    print("B:")
    show_matrix(B)
    print("-"*15)
    
# 転置行列表示
    print("転置行列表示")
    print("A:")
    show_matrix(A.T)
    print("")
    print("B:")
    show_matrix(B.T)
    print("-"*15)

# 逆行列表示
    print("逆行列表示")
    print("A:")
    try:
        show_matrix(A**-1)
    except np.linalg.LinAlgError:
        print("逆行列は存在しない")
    print("")
    print("B:")
    try:
        show_matrix(B**-1)
    except np.linalg.LinAlgError:
        print("逆行列は存在しない")
    print("-"*15)

# Rank表示
    print("Rank表示")
    print("A:")
    print(np.linalg.matrix_rank(A))
    print("")
    print("B:")
    print(np.linalg.matrix_rank(B))
    print("-"*15)

# 積表示
    print("積表示")
    for name, calc in calc_dict.items():
        print(name + ":")
        try:
            show_matrix(eval(calc))
        except ValueError:
            print("積は存在しない")
        print("")
    print("-"*15)
    
#行列式表示
    print("行列式表示")
    print("A:")
    try:
        print(np.linalg.det(A))
    except np.linalg.LinAlgError:
        print("行列式は成立しない")
    print("")
    print("B:")
    try:
        print(np.linalg.det(B))
    except np.linalg.LinAlgError:
        print("行列式は成立しない")
    print("")
    for name, calc in calc_dict.items():
        print(name + ":")
        try:
            print(np.linalg.det(eval(calc)))
        except np.linalg.LinAlgError:
            print("行列式は成立しない")
        except ValueError:
            print("積は存在しない")
        print("")
    print("-"*15)
if __name__ == "__main__":
    # app()
    app(test=True) # デバッグ用

入力行列表示
A:
[ 1 -2  3]
[ 3  1 -5]
[-2  6 -9]

B:
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
---------------
転置行列表示
A:
[ 1  3 -2]
[-2  1  6]
[ 3 -5 -9]

B:
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
---------------
逆行列表示
A:
[3.0000000e+00 1.2952602e-16 1.0000000e+00]
[ 5.28571429 -0.42857143  2.        ]
[ 2.85714286 -0.28571429  1.        ]

B:
逆行列は存在しない
---------------
Rank表示
A:
3

B:
1
---------------
積表示
AA:
[-11  14 -14]
[ 16 -35  49]
[ 34 -44  45]

AB:
[2. 2. 2. 2.]
[-1. -1. -1. -1.]
[-5. -5. -5. -5.]

BA:
積は存在しない

BB:
積は存在しない

tAtA:
[-11  16  34]
[ 14 -35 -44]
[-14  49  45]

tAtB:
積は存在しない

tBtA:
[ 2. -1. -5.]
[ 2. -1. -5.]
[ 2. -1. -5.]
[ 2. -1. -5.]

tBtB:
積は存在しない

AtB:
積は存在しない

tAB:
[2. 2. 2. 2.]
[5. 5. 5. 5.]
[-11. -11. -11. -11.]

BtA:
積は存在しない

tBA:
[  2.   5. -11.]
[  2.   5. -11.]
[  2.   5. -11.]
[  2.   5. -11.]

---------------
行列式表示
A:
7.000000000000004

B:
行列式は成立しない

AA:
48.99999999999991

AB:
行列式は成立しない

BA:
積は存在しない

BB:
積は存在しない

tAtA:
48.99999999999997

tAtB:
積は存在しない

t